### ISSUE TITLE
Input and output ports as defined for Data Mesh?

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/open-data-product-spec#205]
From LinkedIn by Antti Pikkusaari:

"Fascinating! What would be the path to apply the same principles to enable smooth connectivity across organizational boundaries based on data product input and output ports as defined for Data Mesh (by Zhamak Dehghani)."

Source: https://www.linkedin.com/feed/update/urn:li:activity:6937723248105172994?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6937723248105172994%2C6938239581016227840%29

**Comment by niilahti** [comment]
solved in the v1.1 DEV.
