### ISSUE TITLE
Data Product content sample

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/open-data-product-spec#211]
**Idea Description**
Add element in which a sample of the data can be added. Customers often want to see the data and sample is often enough. Looking at the sample is different compared to looking at Data Product content Schema. Both can however be used in getting more familiar with the data product content. The latter is also suitable for validating the data stream. 

**Screenshots**
None

**Comment by niilahti** [comment]
will be solved in the v1.1DEV.
